version: 0.2
env:
  variables:
    APPNAME: "laa-saml-mock-idp"
    ACCOUNT: "Account Number"
phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install -y openjdk-8-jdk
      - apt-get install --reinstall ca-certificates-java
      - ls /etc/ssl/certs/java/cacerts
      - ls /usr/lib/jvm/
      - rm /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/security/cacerts
      - ln -s /etc/ssl/certs/java/cacerts /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/security/cacerts
      - echo Installing maven...
      - wget http://apache.mirror.anlx.net/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
      - tar -zxvf apache-maven-3.5.2-bin.tar.gz
      - echo $PWD
      - MAVEN_HOME=$PWD/apache-maven-3.5.2
      - echo Maven home set to $MAVEN_HOME
      - PATH=$PATH:$MAVEN_HOME/bin
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region eu-west-2)
      - DOCKER_TAG=$APPNAME:`date -u "+%Y%m%d%H%M"`
      - echo Created docker tag $DOCKER_TAG
  build:
    commands:
      - REPOSITORY_URI=$ACCOUNT.dkr.ecr.eu-west-2.amazonaws.com/$DOCKER_TAG
      - echo Created docker target $REPOSITORY_URI
      - echo Starting maven build on `date`...
      - mvn install -e
      - echo Building the Docker image...
      - docker build mujina-idp/ -t $DOCKER_TAG
      - docker tag $DOCKER_TAG $REPOSITORY_URI
  post_build:
    commands:
      - echo Using docker image tag $DOCKER_TAG
      - echo Build completed on `date`
      - echo Pushing the Docker image to... $REPOSITORY_URI
      - docker push $REPOSITORY_URI
      - echo '{ "tag":"'$DOCKER_TAG'" }' >> build_tag.json
      - cat build_tag.json
artifacts:
  files:
      - mujina-idp/target/laa-saml-mock-idp-1.0.0.jar
      - build_tag.json
  discard-paths: yes
